#!/usr/bin/env python
import cgi
import cgitb
cgitb.enable()
import os
from datetime import datetime


default = "No Value Present"


print("Content-Type: text/html")
print("")
script = "cgi_2.py"
today = datetime.now()
month = today.strftime("%B")
day = today.strftime("%d")
year = today.strftime("%Y")
ip = os.environ["REMOTE_ADDR"]

body = """<html>
<head>
<title>Lab 1 - CGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running {script}</p>
<p>Today is {month} {day}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>""".format(
    software=os.environ.get('SERVER_SOFTWARE', default),
    script=script,
    month=month,
    day=day,
    year=year,
    client_ip=ip
)
print(body)
